### ISSUE TITLE
Unable to parse interpolation with concatenation

### ISSUE THREAD

**Issue by mahtd** [postcss/postcss-scss#4]
The parser is able to handle `#{$name} { }`, but adding any other strings around the selector, such as `.#{$name} { }`, results in a css syntax error.

Using this unit test:

```
    it('parses interpolation concatenation', () => {
        let root = parse('.#{$name} { }');
        expect(root.first.selector).to.eql('.#{$name}');
    });
```

It produces this error:

```
     CssSyntaxError: <css input>:1:4: Unknown word
  .#{$name} { }
     ^
      at Object.scssParse [as default] (lib/scss-parse.es6:10:12)
      at Context.<anonymous> (test/parse.es6:75:20)
```

**Comment by ai** [comment]
Fixed df58d8a

**Comment by ai** [comment]
Released 0.1.2

**Comment by mahtd** [comment]
Thanks for fixing this so quickly. I expanded the unit test a bit (which I guess I should have done in the first place), and I'm still getting the syntax error in the property:

```
    it('parses interpolation inside word', () => {
        let root = parse('.#{class}:hover { border-#{$side}-width: #{$width}px; }');
        expect(root.first.selector).to.eql('.#{class}:hover');
        expect(root.first.first.prop).to.eql('border-#{$side}-width');
        expect(root.first.first.value).to.eql('#{$width}px');
    });
```

Error:

```
  1) SCSS Parser parses interpolation inside word:
     CssSyntaxError: <css input>:1:26: Unknown word
  .#{class}:hover { border-#{$side}-width: #{$width}px; }
                           ^
      at Object.scssParse [as default] (lib/scss-parse.es6:10:12)
      at Context.<anonymous> (test/parse.es6:75:20)
```
